package:
  name: bioconductor-hmmcopy-single-cell
  version: 1.32.0
source:
  fn: HMMcopy_1.32.0.tar.gz
  url: https://bioconductor.org/packages/3.12/bioc/src/contrib/HMMcopy_1.32.0.tar.gz
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r >=4.0.0'
    - 'r-data.table'
    - 'r-reshape2'
  run:
    - 'r >=4.0.0'
    - 'r-data.table'
    - 'r-reshape2'
    - 'r-getopt'
    - 'r-plyr'
test:
  commands:
    - '$R -e "library(''HMMcopy'')"'
about:
  home: http://bioconductor.org/packages/HMMcopy/
  summary: 'Corrects GC and mappability biases for readcounts (i.e. coverage) in non-overlapping windows of fixed length
    for single whole genome samples, yielding a rough estimate of copy number for furthur analysis. Designed for rapid
    correction of high coverage whole genome tumour and normal samples.'

