#!/usr/bin/env python

import os
import fnmatch
import argparse

def find_files(directory, pattern):
    for root, dirs, files in os.walk(directory):
        for basename in files:
            if fnmatch.fnmatch(basename, pattern):
                filename = os.path.join(root, basename)
                yield filename

if __name__ == '__main__':
    boost_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../src/boost/'))

    parser = argparse.ArgumentParser()
    parser.add_argument('boost_library_name', help='Name of the boost library')
    args = parser.parse_args()

    boost_lib_dir = os.path.join(boost_dir, 'libs/{}/src'.format(args.boost_library_name))

    lib_sources = list(find_files(boost_lib_dir, '*.cpp'))

    if len(lib_sources) == 0:
        raise Exception('no sources found for boost library {}'.format(args.boost_library_name))

    print ' '.join(lib_sources)

